### ISSUE TITLE
Make settings store the last used com port for arduino executor

### ISSUE THREAD

**Issue by stixes** [Noloxs/hell_snake#30]
Restarting the app resets port selection, leading to not working macros is wrong port is used.

-- To replicate
have 2 or more comm ports occupied, one being the arduino.
Select comm device in menu.
Restart app
Play game, use macros.
-- Expected
Macros work as intended
-- Actual
Macros wont work because commport has reset to non-leonardo device.

**Comment by Noloxs** [comment]
It can also be replicated simply by having a single Arduino connected and then restarting the app.

Suggested fix is to auto connect to lasted device confirmed to work.
